Disable incomplete page in 0.5.0
apache/submarine pull request #424
Opened 2020-10-01 12:36 UTC by ByronHsu

### What is this PR for?

1. Redirect root page to experiment/
2. Disable route and button for data/, model/, workspace/, interpreter/

### What type of PR is it?

[Hot Fix]

### Todos

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-649

### How should this be tested?
https://travis-ci.org/github/ByronHsu/submarine/builds/731919190

### Screenshots (if appropriate)
![Screen Shot 2020-10-01 at 8 35 19 PM](https://user-images.githubusercontent.com/24364830/94809834-c1673680-0425-11eb-9721-9335968bb676.png)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

2020-10-01 14:43 UTC, xunliu reviewed
@ByronHsu Please added `SUBMARINE-649` to PR title.
like., SUBMARINE-649. Disable incomplete pages in 0.5.0

2020-10-02 04:43 UTC, jiwq requested changes
Thanks @ByronHsu for the work. Please check my request changes.

2020-10-02 04:43 UTC, jiwq commented on submarine-workbench/workbench-web-ng/src/app/pages/workbench/workbench.component.ts
> +      routerLink: '/workbench/home',
```suggestion
      routerLink: '/workbench/home'
```

2020-10-02 04:43 UTC, jiwq commented on submarine-workbench/workbench-web-ng/src/app/pages/workbench/workbench-routing.module.ts
> +function disablePage(routes: Routes): Routes{
```suggestion
function disablePage(routes: Routes): Routes {
```

2020-10-02 12:59 UTC, ByronHsu commented
@jiwq Thanks for your help! 
I'm using vscode to develop, and also install the prettier package.
However, it did not detect this formatting problem automatically.
Is this normal? Or maybe my vscode setting is wrong.

2020-10-02 13:43 UTC, kevin85421 commented
@ByronHsu Thank you for your contribution! 

The home page is not included in release 0.5, and thus needs to be disabled too.

2020-10-02 14:15 UTC, ByronHsu commented
@kevin85421 ok! I have added it!

2020-10-02 14:25 UTC, kevin85421 commented
This issue is blocked by #425, and thus #425 should be merged to master prior to this issue. With the rebase of #425, this issue should be able to pass the E2E integration tests.

2020-10-04 15:16 UTC, pingsutw reviewed
Thanks @ByronHsu for the contribution

2020-10-04 15:16 UTC, pingsutw commented on submarine-workbench/workbench-web-ng/src/app/pages/workbench/workbench.component.html
> +        [nzDisabled]="menu.disabled"
```suggestion
```
Duplicate with line 47

2020-10-04 15:36 UTC, pingsutw approved these changes
LGTM

2020-10-04 15:42 UTC, closed without merging