SUBMARINE-708. Add mailing list subscription link
apache/submarine pull request #499
Opened 2021-01-26 09:33 UTC by aeioulisa

### What is this PR for?
Add mailing list subscription link in Readme

### What type of PR is it?
[Documentation]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-708

### How should this be tested?

### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/30621230/105827140-961fdd00-5ffc-11eb-978a-550878fa9d15.png)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

2021-01-26 11:16 UTC, cxorm reviewed
Thanks @aeioulisa for the work. 
Overall LGTM, one question inlined.

2021-01-26 11:16 UTC, cxorm commented on docs/community/README.md
> +Mailing list
IMHO it is a  redundant line, 
feel free to let me know why we need this line if I miss something.

2021-01-26 11:51 UTC, cxorm approved these changes
Thank you @aeioulisa for the fix.
I'm +1 for it.

2021-01-26 11:53 UTC, cxorm commented
Hi @pingsutw,
Could you be so kind as to take a look on this PR, thanks.

2021-01-26 12:13 UTC, pingsutw approved these changes
+1

2021-01-26 13:09 UTC, lowc1012 commented on docs/community/README.md
> +## Mailing list
Mailing lists

2021-01-26 13:55 UTC, lowc1012 requested changes

2021-01-26 13:55 UTC, lowc1012 commented on docs/community/README.md
> ++ [Commits](https://lists.apache.org/list.html?commits@submarine.apache.org) : [subscribe](commits-subscribe@submarine.apache.org), [unsubscribe](commits-unsubscribe@submarine.apache.org), [archives]
The links for subscribing and unsubscribing should be "mailto:xxxxx@submarine.apache.org"

2021-01-26 15:44 UTC, lowc1012 approved these changes
LGTM. @aeioulisa  Thanks!

2021-01-27 04:36 UTC, xunliu approved these changes
@aeioulisa Thank you for contributions.
Will merge if no more comments.

2021-01-27 04:40 UTC, closed without merging